import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Header global */}
        <header className="bg-white shadow-md flex items-center px-6 py-3 max-w-7xl mx-auto">
          <Image
            src="/resources/LOGO.png"
            alt="Logo ECIbienestar"
            width={40}
            height={40}
          />
          <h1 className="ml-4 text-xl font-bold text-gray-900">ECIbienestar</h1>
        </header>

        {/* Contenido principal */}
        {children}
      </body>
    </html>
  );
}
