'use client';

import { usePathname, useRouter } from 'next/navigation';
import Image from 'next/image';
import { Geist, Geist_Mono } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const router = useRouter();

  const showLogout =
    pathname?.startsWith('/sportLoans/adminPage') ||
    pathname?.startsWith('/sportLoans/userPage') ||
    pathname?.startsWith('/sportLoans/generalServicesPage');

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('userId');
    router.push('/');
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900`}>
        {/* Header global - ancho completo */}
        <header className="bg-white shadow-md w-full">
          <div className="max-w-7xl mx-auto flex items-center px-6 py-6 relative">
            <Image
              src="/resources/LOGO.png"
              alt="Logo ECIbienestar"
              width={64}
              height={64}
            />
            <h1 className="ml-4 text-3xl font-bold text-gray-900 flex-grow">
              ECIbienestar - Gestión de Préstamos Deportivos
            </h1>

            {showLogout && (
              <button
                onClick={handleLogout}
                className="absolute right-6 top-1/2 transform -translate-y-1/2 bg-[#990000] text-white px-4 py-2 rounded font-semibold hover:bg-red-600 hover:text-black transition"
              >
                Cerrar sesión
              </button>
            )}
          </div>
        </header>

        {/* Contenido principal */}
        {children}
      </body>
    </html>
  );
}
